a = int(input("Enter the value of a:"))
b = int(input("Enter the value of b:"))
A = a+b
S = a-b
M = a*b
D = a/b
FD = a//b
MD = a%b
E = a**b
T = A+S+M+D+FD+MD+E
print("A=", A)
print("S=", S)
print("M=", M)
print("D=", D)
print("FD=", FD)
print("MD=", MD)
print("E=", E)
print("T=", T)
