print("Comparisonal or Relational operators:")
print("-------------------------------------")
print("A Boolean value (True / False)\n")
print("< = Less than\n")
print("> = Greater than\n")
print("<= = Less than or equal to\n")
print(">= = Greater than or equal to\n")
print("== = equal to\n")
print("!= = Not equal to\n")
